name: greengo_logistics
description: App para gestionar entregas sostenibles en bicicleta
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  
  # Animations (opcional para futuras mejoras)
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (puedes agregar imágenes o animaciones Rive aquí)
  # assets:
  #   - assets/images/
  #   - assets/animations/
